package ca.jahed.rtpoet.rtmodel.types.primitivetype

object RTBool : RTPrimitiveType("bool")
object RTChar : RTPrimitiveType("char")
object RTDouble : RTPrimitiveType("double")
object RTFloat : RTPrimitiveType("float")
object RTInt : RTPrimitiveType("int")
object RTInt8 : RTPrimitiveType("int8_t")
object RTInt16 : RTPrimitiveType("int16_t")
object RTInt32 : RTPrimitiveType("int32_t")
object RTInt64 : RTPrimitiveType("int64_t")
object RTLong : RTPrimitiveType("long")
object RTLongDouble : RTPrimitiveType("long double")
object RTShort : RTPrimitiveType("short")
object RTUnsignedChar : RTPrimitiveType("unsigned char")
object RTUnsignedInt : RTPrimitiveType("unsigned int")
object RTUnsignedInt8 : RTPrimitiveType("uint8_t")
object RTUnsignedInt16 : RTPrimitiveType("uint16_t")
object RTUnsignedInt32 : RTPrimitiveType("uint32_t")
object RTUnsignedInt64 : RTPrimitiveType("uint64_t")
object RTUnsignedLong : RTPrimitiveType("unsigned long")
object RTUnsignedShort : RTPrimitiveType("unsigned short")
object RTVoid : RTPrimitiveType("void")
object RTWChar : RTPrimitiveType("wchar_t")